// <auto-generated />
namespace DbManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Created_NEW_Entity_Transaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Created_NEW_Entity_Transaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201911250939490_Created_NEW_Entity_Transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
