// <auto-generated />
namespace DbManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Relation_Between_Buy_AND_Transaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relation_Between_Buy_AND_Transaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201911250941416_Relation_Between_Buy_AND_Transaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
