// <auto-generated />
namespace DbManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Created_Buy_enity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Created_Buy_enity));
        
        string IMigrationMetadata.Id
        {
            get { return "201911181016223_Created_Buy_enity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
