// <auto-generated />
namespace DbManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_columns_PriceAndWholeSalePrice_in_Warehouse_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_columns_PriceAndWholeSalePrice_in_Warehouse_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202004021005008_Create_columns_PriceAndWholeSalePrice_in_Warehouse_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
