// <auto-generated />
namespace DbManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_columns_UserNameAndDateTime_from_Buy_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_columns_UserNameAndDateTime_from_Buy_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202004021046045_remove_columns_UserNameAndDateTime_from_Buy_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
