// <auto-generated />
namespace DbManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_EntityGender : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_EntityGender));
        
        string IMigrationMetadata.Id
        {
            get { return "202005131639168_added_EntityGender"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
