<%@ Page Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="ProducerView.aspx.cs" Inherits="MarketProject.View.AdminPanel.ProducerView" Async="true" %>


<asp:Content ID="Content2" runat="server" contentplaceholderid="WebPageContent" ViewStateMode="Enabled">



     
        <div class="auto-style1">
            <div class="auto-style2">
                <br />
                <asp:Label ID="lblTitle" runat="server" Font-Size="X-Large" Text="Poducer Managment"></asp:Label>
                <br />
                <br />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <br />
                <br />
            <asp:Label ID="lblName" runat="server" Text="Company Name"></asp:Label>
&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="txtName" runat="server"></asp:TextBox>
&nbsp;&nbsp;
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtName" ErrorMessage="* Is Empty" ForeColor="Red"></asp:RequiredFieldValidator>
            <br />
            <br />
            <asp:Label ID="lblCountry" runat="server" Text="Country"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="txtCountry" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Button ID="btnSave" runat="server" OnClick="BtnSave_Click" Text="Save" Width="242px" />
                <br />
                <br />
                <asp:Literal ID="Literal1" runat="server"></asp:Literal>
                <br />
                <br />
            </div>
            <asp:GridView ID="gridProducer" runat="server" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleted="GridProducer_RowDeleted" OnRowDeleting="GridProducer_RowDeleting" Width="430px">
            </asp:GridView>
            <div class="auto-style2">
<asp:ScriptManager runat="server" ID="MessageBoxUserControl1" EnablePageMethods="True">
</asp:ScriptManager>
                <br />
                <br />
                <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>
                <br />
            <br />
            </div>
        </div>
    </asp:Content>

