<%@ Page Language="C#" MasterPageFile="~/MasterPage.Master"  ViewStateMode="Disabled"   AutoEventWireup="true" CodeBehind="BuyView.aspx.cs"  
    Inherits="MarketProject.View.Market.BuyView"   Async="true"  EnableEventValidation="true"
    
    %>

<%@ Register Src="~/View/Components/ProductsControl.ascx" TagPrefix="uc1" TagName="ProductsControl" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content  ID="Content2" runat="server" contentplaceholderid="WebPageContent" ViewStateMode="Enabled">



       <div class="backGroundBuy">
               <asp:Label CssClass="buyPageTitle" Width="100%" ID="lblTitle" runat="server" Text="Buy Manager"></asp:Label>
                <div>
                    <uc1:ProductsControl  runat="server" id="ProductsControl" />
                </div>

           
            
            <div class="auto-style3">
                <asp:Label CssClass="LableStyle" ID="lblCount" runat="server" Text="Count"></asp:Label>
                <asp:TextBox CssClass="buyProdTxtBoxCount" ID="txtCount" runat="server" TabIndex="1" OnTextChanged="txtCount_TextChanged" ></asp:TextBox>
            </div>

            <div>
                <asp:Label CssClass="LableStyle" ID="lblPrice" runat="server" Text="Price"></asp:Label>
                <asp:TextBox CssClass="buyProdTxtBoxPrice" ID="txtPrice" runat="server" MaxLength="7" TabIndex="2" OnTextChanged="txtCount_TextChanged"></asp:TextBox>
            </div>
             <div>
                <asp:Label CssClass="LableStyle" ID="lblRetailSalePrice" runat="server" Text="Retail Price"></asp:Label>
                <asp:TextBox CssClass="buyProdTxtBoxRetailPrice" ID="txtBoxRetailPrice" runat="server" MaxLength="9" TabIndex="2" ></asp:TextBox>
            </div>
             <div>
                <asp:Label CssClass="LableStyle" ID="lblWholeSalePrice" runat="server" Text="WholeSale Price"></asp:Label>
                <asp:TextBox CssClass="buyProdTxtBoxPrice" ID="txtWholeSalePrice" runat="server" MaxLength="7" TabIndex="2" ></asp:TextBox>
            </div>

           

            <div>
                <asp:Label CssClass="LableStyle" ID="lblDiscount" runat="server" Text="Discount" Visible="False"></asp:Label>
                <asp:TextBox CssClass="buyProdTxtBoxDiscount" ID="txtDiscount" runat="server" MaxLength="7" TabIndex="3" Visible="False"></asp:TextBox>
            </div>
        <div class="divTotal">
                <asp:Label CssClass="TotalMoney" ID="lblTotal" runat="server" Font-Bold="False" Font-Size="Medium" ForeColor="Red" Text="Total Price   "></asp:Label>

     
                <asp:Label CssClass="TotalMoney" ID="lbltotalMoney" runat="server"></asp:Label>

     
            </div>
    <div class="buyBasketComplateOrder">
        <div class="DivToCenter">
                <asp:Button CssClass="buttonStyle" ID="AddToBasket" runat="server" Text="Add to basket" OnClick="ImgButtonAddToCard_Click" />
                <asp:Button CssClass="buttonStyle" Text="Complate order" ID="ImageButtonComplateOrder" runat="server"  OnClick="ImageButtonComplateOrder_Click" Visible="False" />
                <asp:Button CssClass="buttonStyle" Text="Cancel Order" ID="buttonCancel" runat="server" Visible="False" OnClick="canel_Click" />

        </div>


       
                <br />
                <br />
                <asp:GridView ID="GridViewBasket" runat="server" AllowPaging="True" AutoGenerateColumns="False" CellPadding="4" DataSourceID="ObjectDataSourceBuyView" ForeColor="#333333" GridLines="None" RowHeaderColumn="ProductName" ShowFooter="True" ShowHeaderWhenEmpty="True" AutoGenerateDeleteButton="True" CellSpacing="5" HorizontalAlign="Center">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:BoundField DataField="ProductName" HeaderText="ProductName" ReadOnly="True" SortExpression="ProductName" />
                        <asp:BoundField DataField="Count" HeaderText="Count" SortExpression="Count" />
                        <asp:BoundField DataField="Discount" HeaderText="Discount" SortExpression="Discount" />
                        <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                        <asp:BoundField DataField="RetailPrice" HeaderText="RetailPrice" SortExpression="RetailPrice" />
                        <asp:BoundField DataField="WholeSalePrice" HeaderText="WholeSalePrice" SortExpression="WholeSalePrice" />
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" HorizontalAlign="Center" VerticalAlign="Middle" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>


       
      </div>
        <div class="GridStyle">
            <asp:ObjectDataSource ID="ObjectDataSourceBuyView" runat="server" SelectMethod="GetItems" TypeName="MarketProject.View.Market.BuyView" DeleteMethod="RemoveItem" SelectCountMethod="GetItems">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
            </asp:ObjectDataSource>
         
        </div>

       </div>
      
      

<asp:Button ID="popupShowButton" CssClass="InvisibleButton" runat="server" />
    <asp:ScriptManager runat="server">

    </asp:ScriptManager>
<cc1:ModalPopupExtender ID="modalPopup" runat="server" PopupControlID="panelPopup" TargetControlID="popupShowButton"
    CancelControlID="popupCloseButton" BackgroundCssClass="modalBackground">
</cc1:ModalPopupExtender>
<asp:Panel ID="panelPopup" runat="server" CssClass="modalPopup" align="center" Visible="false">
    <iframe  id="irm1" src="~/Popup/Attention.aspx" runat="server" ></iframe>
   <br/>
    <asp:Button ID="popupCloseButton" runat="server" Text="x" />
</asp:Panel>

          
        
</asp:Content>